version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=itsme
      - POSTGRES_PASSWORD=1123ert567ui

